version: "3.9"

services:
  marketplace:
    build:
      context: ./marketplace
      network: host
    container_name: marketplace
    ports:
      - "8080:8080"
    environment:
      # TODO: Remover essa env quando o cliente Feign tiver sido substituído por uma classe de integração que faz requests com WebClient
      RECEIVER_API_URL: http://receiver:8081
  receiver:
    build:
      context: ./receiver
      network: host
    container_name: receiver
    ports:
      - "8081:8081"