services:
  marketplace:
    build:
      context: ./marketplace
      network: host
    container_name: marketplace
    ports:
      - "8080:8080"
  receiver:
    build:
      context: ./receiver
      network: host
    container_name: receiver
    ports:
      - "8081:8081"
    environment:
      MARKETPLACE_API_URL: http://marketplace:8080